name: Don's Bōjutsu
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter: pygments
permalink: pretty
author: Francisco Granados
description: 'Memories for code, music and life.'
exclude: ['LICENSE', 'Procfile', 'README.md', 'Guardfile', 'Gemfile', 'Gemfile.lock']
