name: Don's Bōjutsu
markdown: redcarpet
highlighter: pygments
permalink: pretty
author: Francisco Granados
description: 'Memories for code, music and life.'
exclude: ['LICENSE', 'Procfile', 'README.md', 'Guardfile', 'Gemfile', 'Gemfile.lock']
