name: Don's Bōjutsu
permalink: pretty
author: Francisco Granados
description: 'Blog of Francisco Granados aka gzfrancisco, developer and economist.'
tagline: 'Memories for code, music and life.'
keywords: 'gzfrancisco blog, Francisco Granados, iOS developer, ruby programmer'
timezone: America/Mexico_City
url: http://gzfrancisco.name

exclude: ['.gitignore', 'Gemfile', 'Gemfile.lock', 'LICENSE', 'Procfile', 'README.md']
