name: Don's Bōjutsu
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter: pygments
permalink: pretty
author: Francisco Granados
description: 'Blog of Francisco Granados aka gzfrancisco, developer and economist.'
keywords: 'gzfrancisco blog, Francisco Granados, iOS developer, ruby programmer'
timezone: America/Mexico_City
exclude: ['.gitignore', 'Gemfile', 'Gemfile.lock', 'LICENSE', 'Procfile', 'README.md']
