name: Don's Bōjutsu
permalink: pretty
author: Francisco Granados Gómez
description: 'Blog of gzfrancisco; economist, engineer, scuba diver, and music lover.
tagline: 'Thoughs on technology, economy, politics, music, and life.'
keywords: 'gzfrancisco blog, Francisco Granados Gomez, software engineer'
timezone: America/Pacific_Time_Zone
url: https://gzfrancisco.github.io

exclude: ['.gitignore', 'Gemfile', 'Gemfile.lock', 'LICENSE', 'Procfile', 'README.md']
